import * as z from "zod"

export const finality_providers_delegationsModel = z.object({
  id: z.number().int(),
  babylon_pk: z.string().nullish(),
  babylon_address: z.string().nullish(),
  btc_pk: z.string(),
  btc_address: z.string().nullish(),
  fp_btc_pk_list: z.string().array(),
  start_height: z.bigint().nullish(),
  end_height: z.bigint().nullish(),
  total_sat: z.number(),
  active: z.boolean().nullish(),
  status_desc: z.string().nullish(),
  staking_tx_hash: z.string(),
  staking_tx_hex: z.string().nullish(),
  staking_output_idx: z.bigint(),
  staking_timestamp: z.bigint(),
  staking_block_height: z.bigint(),
  staking_peroid: z.bigint().nullish(),
  unbonding_tx_hex: z.string().nullish(),
  unbonding_tx_hash: z.string().nullish(),
  unboding_time: z.bigint().nullish(),
  unbonding_sat: z.number(),
  unbonding_delegator_sig: z.string().nullish(),
  unbonding_covenant_sig: z.string().nullish(),
  unbonding_timestamp: z.bigint().nullish(),
  unboding_slashing_tx_hex: z.string().nullish(),
  unbonding_slashing_tx_hash: z.string().nullish(),
  unbonding_slashing_delegator_sig: z.string().nullish(),
  unbonding_slashing_covenant_sig: z.string().nullish(),
  slashing_tx_hex: z.string().nullish(),
  slashing_tx_hash: z.string().nullish(),
  slashing_delegator_sig: z.string().nullish(),
  slashing_covenant_sig: z.string().nullish(),
  slashing_timestamp: z.bigint().nullish(),
  withdrawal_tx_hex: z.string().nullish(),
  withdrawal_tx_hash: z.string().nullish(),
  withdrawal_timestamp: z.bigint().nullish(),
  inserted_at: z.date(),
  updated_at: z.date(),
})
